import type { Metadata } from 'next';
import { FontContextProvider, ThemeContextProvider } from '@/src/context';
import './globals.css';
import { ToastContextProvider } from '@/src/context/toastContext';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="ease-in-out duration-75">
        <FontContextProvider>
          <ThemeContextProvider>
            <ToastContextProvider>{children}</ToastContextProvider>
          </ThemeContextProvider>
        </FontContextProvider>
      </body>
    </html>
  );
}
