import type { Metadata } from 'next';
import {
  FontContextProvider,
  NoteContextProvider,
  ThemeContextProvider,
} from '@/src/context';
import './globals.css';
import { ToastContextProvider } from '@/src/context/toastContext';
import { ModalContextProvider } from '@/src/context/modalContext';
import { SearchContextProvider } from '../context/searchContext';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="ease-in-out duration-75">
        <FontContextProvider>
          <ThemeContextProvider>
            <ModalContextProvider>
              <NoteContextProvider>
                <SearchContextProvider>
                  <ToastContextProvider>{children}</ToastContextProvider>
                </SearchContextProvider>
              </NoteContextProvider>
            </ModalContextProvider>
          </ThemeContextProvider>
        </FontContextProvider>
      </body>
    </html>
  );
}
